slug = "whats-on-the-menu"
title = "What's on the Menu?"
author = "bliutech"
value = 20
description = """You're invited to Hawthorne, the restaurant of world famous chef, Julian Slowik. Try to order something on *the Menu*. Visit [https://ao.bliu.tech:8080](https://ao.bliu.tech:8080)."""
tags = ["intro"]
files = []
flag = "flag{jUs1_8_pLa1n_c3e5eBur9eR}"
enabled = true
